package main

import (
	"fmt"
	"log"
	"net/url"
	"os"
	"time"

	"github.com/godoes/gorm-oracle"
	"github.com/joho/godotenv"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"
)

func main() {
	fmt.Println("=====================================")
	fmt.Println("Oracle ATP Connection Test")
	fmt.Println("=====================================\n")

	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, using environment variables")
	}

	// Get configuration
	dbType := os.Getenv("DB_TYPE")
	user := os.Getenv("DB_USER")
	password := os.Getenv("DB_PASSWORD")

	if user == "" {
		user = "ADMIN"
	}

	fmt.Println("📋 Configuration:")
	fmt.Printf("   DB_TYPE: %s\n", dbType)
	fmt.Printf("   DB_USER: %s\n", user)
	fmt.Printf("   Password: ****\n\n")

	// Build DSN
	var dsn string
	if envDSN := os.Getenv("DATABASE_URL"); envDSN != "" {
		dsn = envDSN
		fmt.Println("📌 Using DATABASE_URL from environment")
	} else {
		// Build Oracle ATP URL from environment variables
		host := os.Getenv("DB_HOST")
		port := os.Getenv("DB_PORT")
		service := os.Getenv("DB_SERVICE")
		sslEnabled := os.Getenv("DB_SSL")

		if host == "" || port == "" || service == "" {
			fmt.Println("❌ Missing database configuration. Please set DB_HOST, DB_PORT, and DB_SERVICE")
			os.Exit(1)
		}

		encodedPassword := url.QueryEscape(password)
		if sslEnabled == "true" {
			dsn = fmt.Sprintf("oracle://%s:%s@%s:%s/%s?SSL=true",
				user, encodedPassword, host, port, service)
		} else {
			dsn = fmt.Sprintf("oracle://%s:%s@%s:%s/%s",
				user, encodedPassword, host, port, service)
		}
		fmt.Println("📌 Using environment variable configuration")
	}

	fmt.Println("\n🔌 Connection Details:")
	fmt.Printf("   Host: %s\n", os.Getenv("DB_HOST"))
	fmt.Printf("   Port: %s\n", os.Getenv("DB_PORT"))
	fmt.Printf("   Service: %s\n", os.Getenv("DB_SERVICE"))
	fmt.Printf("   SSL: %s\n", os.Getenv("DB_SSL"))
	fmt.Println("   Driver: godoes/gorm-oracle (using sijms/go-ora)")

	// Connect to database
	fmt.Println("\n🔄 Connecting to Oracle ATP...")
	startTime := time.Now()

	db, err := gorm.Open(oracle.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent), // Silent for cleaner output
	})
	if err != nil {
		fmt.Printf("❌ Failed to connect: %v\n", err)
		os.Exit(1)
	}

	connectionTime := time.Since(startTime)
	fmt.Printf("✅ Connected successfully! (took %v)\n", connectionTime)

	// Get SQL DB instance
	sqlDB, err := db.DB()
	if err != nil {
		fmt.Printf("❌ Failed to get DB instance: %v\n", err)
		os.Exit(1)
	}
	defer sqlDB.Close()

	// Test 1: Ping
	fmt.Println("\n📍 Test 1: Ping Database")
	startTime = time.Now()
	if err := sqlDB.Ping(); err != nil {
		fmt.Printf("   ❌ Ping failed: %v\n", err)
	} else {
		fmt.Printf("   ✅ Ping successful (took %v)\n", time.Since(startTime))
	}

	// Test 2: Get Database Info
	fmt.Println("\n📍 Test 2: Database Information")

	var dbVersion string
	db.Raw("SELECT VERSION FROM V$INSTANCE").Scan(&dbVersion)
	if dbVersion != "" {
		fmt.Printf("   • Version: %s\n", dbVersion)
	}

	var dbName string
	db.Raw("SELECT NAME FROM V$DATABASE").Scan(&dbName)
	if dbName != "" {
		fmt.Printf("   • Database: %s\n", dbName)
	}

	var serviceName string
	db.Raw("SELECT SYS_CONTEXT('USERENV', 'SERVICE_NAME') FROM DUAL").Scan(&serviceName)
	if serviceName != "" {
		fmt.Printf("   • Service: %s\n", serviceName)
	}

	var currentUser string
	db.Raw("SELECT USER FROM DUAL").Scan(&currentUser)
	if currentUser != "" {
		fmt.Printf("   • Current User: %s\n", currentUser)
	}

	var sessionID int
	db.Raw("SELECT SYS_CONTEXT('USERENV', 'SESSIONID') FROM DUAL").Scan(&sessionID)
	if sessionID > 0 {
		fmt.Printf("   • Session ID: %d\n", sessionID)
	}

	// Test 3: Connection Pool Stats
	fmt.Println("\n📍 Test 3: Connection Pool")
	stats := sqlDB.Stats()
	fmt.Printf("   • Open Connections: %d\n", stats.OpenConnections)
	fmt.Printf("   • In Use: %d\n", stats.InUse)
	fmt.Printf("   • Idle: %d\n", stats.Idle)

	// Test 4: Simple Query
	fmt.Println("\n📍 Test 4: Simple Query Test")
	var result int
	startTime = time.Now()
	if err := db.Raw("SELECT 1+1 FROM DUAL").Scan(&result).Error; err != nil {
		fmt.Printf("   ❌ Query failed: %v\n", err)
	} else {
		fmt.Printf("   ✅ Query result: 1+1 = %d (took %v)\n", result, time.Since(startTime))
	}

	// Test 5: Table Operations
	fmt.Println("\n📍 Test 5: Table Operations")

	type TestModel struct {
		ID        uint   `gorm:"primaryKey"`
		Name      string `gorm:"size:100"`
		Value     int
		CreatedAt time.Time
	}

	tableName := "connection_test"

	// Drop if exists
	db.Exec(fmt.Sprintf("DROP TABLE %s", tableName))

	// Create table using raw SQL (more reliable for Oracle)
	createSQL := fmt.Sprintf(`
		CREATE TABLE %s (
			id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name VARCHAR2(100),
			value NUMBER,
			created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
		)
	`, tableName)

	if err := db.Exec(createSQL).Error; err != nil {
		fmt.Printf("   ❌ Create table failed: %v\n", err)
	} else {
		fmt.Println("   ✅ Table created")

		// Insert test data
		insertSQL := fmt.Sprintf("INSERT INTO %s (name, value) VALUES (:1, :2)", tableName)
		if err := db.Exec(insertSQL, "Test Record", 42).Error; err != nil {
			fmt.Printf("   ❌ Insert failed: %v\n", err)
		} else {
			fmt.Println("   ✅ Data inserted")

			// Query data
			var count int64
			db.Raw(fmt.Sprintf("SELECT COUNT(*) FROM %s", tableName)).Scan(&count)
			fmt.Printf("   ✅ Records in table: %d\n", count)

			// Clean up
			if err := db.Exec(fmt.Sprintf("DROP TABLE %s", tableName)).Error; err != nil {
				fmt.Printf("   ❌ Cleanup failed: %v\n", err)
			} else {
				fmt.Println("   ✅ Table dropped")
			}
		}
	}

	// Test 6: GORM AutoMigrate Test
	fmt.Println("\n📍 Test 6: GORM AutoMigrate")

	type GormTest struct {
		ID   uint   `gorm:"primaryKey"`
		Name string `gorm:"size:50"`
	}

	// Set table name
	db = db.Table("gorm_test")

	// Try AutoMigrate
	if err := db.AutoMigrate(&GormTest{}); err != nil {
		fmt.Printf("   ⚠️  AutoMigrate notice: %v\n", err)
	} else {
		fmt.Println("   ✅ AutoMigrate successful")

		// Try to create a record
		testRecord := GormTest{Name: "GORM Test"}
		if err := db.Create(&testRecord).Error; err != nil {
			fmt.Printf("   ❌ GORM Create failed: %v\n", err)
		} else {
			fmt.Printf("   ✅ GORM Create successful (ID: %d)\n", testRecord.ID)

			// Query back
			var found GormTest
			if err := db.First(&found).Error; err != nil {
				fmt.Printf("   ❌ GORM Query failed: %v\n", err)
			} else {
				fmt.Printf("   ✅ GORM Query successful: %+v\n", found)
			}
		}

		// Clean up
		db.Exec("DROP TABLE gorm_test")
	}

	// Test 7: Check existing tables
	fmt.Println("\n📍 Test 7: Existing Tables Check")

	tables := []string{"members", "rooms", "prayers", "invitations"}
	for _, table := range tables {
		var count int
		db.Raw("SELECT COUNT(*) FROM USER_TABLES WHERE UPPER(TABLE_NAME) = UPPER(?)", table).Scan(&count)
		if count > 0 {
			var rowCount int64
			db.Raw(fmt.Sprintf("SELECT COUNT(*) FROM %s", table)).Scan(&rowCount)
			fmt.Printf("   • %s: ✅ exists (%d rows)\n", table, rowCount)
		} else {
			fmt.Printf("   • %s: ❌ not found\n", table)
		}
	}

	// Summary
	fmt.Println("\n=====================================")
	fmt.Println("🎉 Connection Test Complete!")
	fmt.Println("=====================================")
	fmt.Println("\n✅ Oracle ATP is working correctly with:")
	fmt.Println("   • Driver: godoes/gorm-oracle")
	fmt.Println("   • Pure Go: No Oracle Client needed")
	fmt.Println("   • SSL: Secure connection established")
	fmt.Println("   • GORM: ORM features available")
	fmt.Println("\n📝 Note: Some warnings about existing objects are")
	fmt.Println("   normal if tables already exist in the database.")
}

func maskPassword(dsn string) string {
	// Simple masking for Oracle DSN format
	for idx := 0; idx < len(dsn); idx++ {
		if dsn[idx] == '/' {
			for atIdx := idx + 1; atIdx < len(dsn); atIdx++ {
				if dsn[atIdx] == '@' {
					return dsn[:idx+1] + "****" + dsn[atIdx:]
				}
			}
			// Find @ after password
			for j := idx + 1; j < len(dsn); j++ {
				if dsn[j] == '@' {
					return dsn[:idx+1] + "****" + dsn[j:]
				}
			}
		}
	}
	return dsn
}
